namespace EcShop.Infrastructure.Persistence;

public sealed class Category { public long CatId { get; set; } public string CatName { get; set; } = string.Empty; public long ParentId { get; set; } public bool IsShow { get; set; } = true; }
public sealed class Brand { public long BrandId { get; set; } public string BrandName { get; set; } = string.Empty; public string BrandLogo { get; set; } = string.Empty; public string BrandDesc { get; set; } = string.Empty; public string SiteUrl { get; set; } = string.Empty; public bool IsShow { get; set; } = true; }
public sealed class Goods { public long GoodsId { get; set; } public long CatId { get; set; } public string GoodsSn { get; set; } = string.Empty; public string GoodsName { get; set; } = string.Empty; public long BrandId { get; set; } public int GoodsNumber { get; set; } public decimal MarketPrice { get; set; } public decimal ShopPrice { get; set; } public string Keywords { get; set; } = string.Empty; public string GoodsBrief { get; set; } = string.Empty; public string GoodsDesc { get; set; } = string.Empty; public string GoodsThumb { get; set; } = string.Empty; public string GoodsImg { get; set; } = string.Empty; public bool IsOnSale { get; set; } = true; public bool IsDelete { get; set; } public bool IsBest { get; set; } public bool IsNew { get; set; } public bool IsHot { get; set; } public long AddTime { get; set; } }
public sealed class GoodsOption { public long GoodsAttrId { get; set; } public long GoodsId { get; set; } public long AttrId { get; set; } public string AttrValue { get; set; } = string.Empty; public decimal AttrPrice { get; set; } }
public sealed class Product { public long ProductId { get; set; } public long GoodsId { get; set; } public string GoodsAttr { get; set; } = string.Empty; public string ProductSn { get; set; } = string.Empty; public int ProductNumber { get; set; } }
public sealed class ArticleCategory { public long CatId { get; set; } public string CatName { get; set; } = string.Empty; public string CatDesc { get; set; } = string.Empty; public bool IsShow { get; set; } = true; }
public sealed class Article { public long ArticleId { get; set; } public long CatId { get; set; } public string Title { get; set; } = string.Empty; public string Author { get; set; } = string.Empty; public string ArticleDesc { get; set; } = string.Empty; public string Content { get; set; } = string.Empty; public bool IsOpen { get; set; } = true; }
public sealed class Region { public long RegionId { get; set; } public long ParentId { get; set; } public string RegionName { get; set; } = string.Empty; public int RegionType { get; set; } }
public sealed class ShopUser { public long UserId { get; set; } public string UserName { get; set; } = string.Empty; public string Email { get; set; } = string.Empty; public string PasswordHash { get; set; } = string.Empty; }
public sealed class UserSession { public string TokenHash { get; set; } = string.Empty; public long UserId { get; set; } }
public sealed class UserAddress { public long AddressId { get; set; } public long UserId { get; set; } public string Consignee { get; set; } = string.Empty; public long CountryId { get; set; } public long ProvinceId { get; set; } public long CityId { get; set; } public long DistrictId { get; set; } public string Address { get; set; } = string.Empty; public string Zipcode { get; set; } = string.Empty; public string Mobile { get; set; } = string.Empty; public bool IsDefault { get; set; } }
public sealed class CartItem { public long RecId { get; set; } public long UserId { get; set; } public long GoodsId { get; set; } public int GoodsNumber { get; set; } public int Version { get; set; } = 1; }
public sealed class ShippingMethod { public long ShippingId { get; set; } public string ShippingName { get; set; } = string.Empty; public bool Enabled { get; set; } = true; public decimal ShippingFee { get; set; } }
public sealed class PaymentMethod { public long PayId { get; set; } public string PayName { get; set; } = string.Empty; public bool Enabled { get; set; } = true; public decimal PayFee { get; set; } }
public sealed class ShopOrder { public long OrderId { get; set; } public string OrderSn { get; set; } = string.Empty; public long UserId { get; set; } public int OrderStatus { get; set; } public int PayStatus { get; set; } public int ShippingStatus { get; set; } public string Consignee { get; set; } = string.Empty; public string Address { get; set; } = string.Empty; public long ShippingId { get; set; } public string ShippingName { get; set; } = string.Empty; public long PayId { get; set; } public string PayName { get; set; } = string.Empty; public decimal GoodsAmount { get; set; } public decimal ShippingFee { get; set; } public decimal PayFee { get; set; } public decimal OrderAmount { get; set; } public long AddTime { get; set; } public string ClientRequestId { get; set; } = string.Empty; }
public sealed class OrderItem { public long RecId { get; set; } public long OrderId { get; set; } public long GoodsId { get; set; } public string GoodsName { get; set; } = string.Empty; public string GoodsSn { get; set; } = string.Empty; public decimal GoodsPrice { get; set; } public int GoodsNumber { get; set; } }
public sealed class OrderAction { public long ActionId { get; set; } public long OrderId { get; set; } public long UserId { get; set; } public string ActionNote { get; set; } = string.Empty; public long LogTime { get; set; } }
public sealed class ShopComment { public long CommentId { get; set; } public long GoodsId { get; set; } public long UserId { get; set; } public string Content { get; set; } = string.Empty; public bool IsVisible { get; set; } = true; public long AddTime { get; set; } }
public sealed class PaymentLog { public long LogId { get; set; } public long OrderId { get; set; } public string Provider { get; set; } = string.Empty; public string TransactionId { get; set; } = string.Empty; public long PaidAt { get; set; } }
public sealed class GoodsActivity { public long ActivityId { get; set; } public string ActivityType { get; set; } = string.Empty; public string ActivityName { get; set; } = string.Empty; public long GoodsId { get; set; } public long StartTime { get; set; } public long EndTime { get; set; } public bool IsFinished { get; set; } }
