using Microsoft.EntityFrameworkCore;

namespace EcShop.Infrastructure.Persistence;

/// <summary>The unit-of-work boundary for ECSHOP tables. Maps are added URL by URL.</summary>
public sealed class EcShopDbContext(DbContextOptions<EcShopDbContext> options) : DbContext(options)
{
    public DbSet<Category> Categories => Set<Category>();
    public DbSet<Brand> Brands => Set<Brand>();
    public DbSet<Goods> Goods => Set<Goods>();
    public DbSet<GoodsOption> GoodsAttributes => Set<GoodsOption>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<ArticleCategory> ArticleCategories => Set<ArticleCategory>();
    public DbSet<Article> Articles => Set<Article>();
    public DbSet<Region> Regions => Set<Region>();
    public DbSet<ShopUser> Users => Set<ShopUser>(); public DbSet<UserSession> Sessions => Set<UserSession>(); public DbSet<UserAddress> Addresses => Set<UserAddress>(); public DbSet<CartItem> CartItems => Set<CartItem>(); public DbSet<ShippingMethod> ShippingMethods => Set<ShippingMethod>(); public DbSet<PaymentMethod> PaymentMethods => Set<PaymentMethod>(); public DbSet<ShopOrder> Orders => Set<ShopOrder>(); public DbSet<OrderItem> OrderItems => Set<OrderItem>(); public DbSet<OrderAction> OrderActions => Set<OrderAction>(); public DbSet<ShopComment> Comments => Set<ShopComment>(); public DbSet<PaymentLog> PaymentLogs => Set<PaymentLog>(); public DbSet<GoodsActivity> GoodsActivities => Set<GoodsActivity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity => { entity.ToTable("ecs_category"); entity.HasKey(x => x.CatId); entity.Property(x => x.CatId).HasColumnName("cat_id"); entity.Property(x => x.CatName).HasColumnName("cat_name"); entity.Property(x => x.ParentId).HasColumnName("parent_id"); entity.Property(x => x.IsShow).HasColumnName("is_show"); });
        modelBuilder.Entity<Brand>(entity => { entity.ToTable("ecs_brand"); entity.HasKey(x => x.BrandId); entity.Property(x => x.BrandId).HasColumnName("brand_id"); entity.Property(x => x.BrandName).HasColumnName("brand_name"); entity.Property(x => x.BrandLogo).HasColumnName("brand_logo"); entity.Property(x => x.BrandDesc).HasColumnName("brand_desc"); entity.Property(x => x.SiteUrl).HasColumnName("site_url"); entity.Property(x => x.IsShow).HasColumnName("is_show"); });
        modelBuilder.Entity<Goods>(entity => { entity.ToTable("ecs_goods"); entity.HasKey(x => x.GoodsId); entity.Property(x => x.GoodsId).HasColumnName("goods_id"); entity.Property(x => x.CatId).HasColumnName("cat_id"); entity.Property(x => x.GoodsSn).HasColumnName("goods_sn"); entity.Property(x => x.GoodsName).HasColumnName("goods_name"); entity.Property(x => x.BrandId).HasColumnName("brand_id"); entity.Property(x => x.GoodsNumber).HasColumnName("goods_number"); entity.Property(x => x.MarketPrice).HasColumnName("market_price"); entity.Property(x => x.ShopPrice).HasColumnName("shop_price"); entity.Property(x => x.Keywords).HasColumnName("keywords"); entity.Property(x => x.GoodsBrief).HasColumnName("goods_brief"); entity.Property(x => x.GoodsDesc).HasColumnName("goods_desc"); entity.Property(x => x.GoodsThumb).HasColumnName("goods_thumb"); entity.Property(x => x.GoodsImg).HasColumnName("goods_img"); entity.Property(x => x.IsOnSale).HasColumnName("is_on_sale"); entity.Property(x => x.IsDelete).HasColumnName("is_delete"); entity.Property(x => x.IsBest).HasColumnName("is_best"); entity.Property(x => x.IsNew).HasColumnName("is_new"); entity.Property(x => x.IsHot).HasColumnName("is_hot"); entity.Property(x => x.AddTime).HasColumnName("add_time"); });
        modelBuilder.Entity<GoodsOption>(entity => { entity.ToTable("ecs_goods_attr"); entity.HasKey(x => x.GoodsAttrId); entity.Property(x => x.GoodsAttrId).HasColumnName("goods_attr_id"); entity.Property(x => x.GoodsId).HasColumnName("goods_id"); entity.Property(x => x.AttrId).HasColumnName("attr_id"); entity.Property(x => x.AttrValue).HasColumnName("attr_value"); entity.Property(x => x.AttrPrice).HasColumnName("attr_price"); });
        modelBuilder.Entity<Product>(entity => { entity.ToTable("ecs_products"); entity.HasKey(x => x.ProductId); entity.Property(x => x.ProductId).HasColumnName("product_id"); entity.Property(x => x.GoodsId).HasColumnName("goods_id"); entity.Property(x => x.GoodsAttr).HasColumnName("goods_attr"); entity.Property(x => x.ProductSn).HasColumnName("product_sn"); entity.Property(x => x.ProductNumber).HasColumnName("product_number"); });
        modelBuilder.Entity<ArticleCategory>(entity => { entity.ToTable("ecs_article_cat"); entity.HasKey(x => x.CatId); entity.Property(x => x.CatId).HasColumnName("cat_id"); entity.Property(x => x.CatName).HasColumnName("cat_name"); entity.Property(x => x.CatDesc).HasColumnName("cat_desc"); entity.Property(x => x.IsShow).HasColumnName("is_show"); });
        modelBuilder.Entity<Article>(entity => { entity.ToTable("ecs_article"); entity.HasKey(x => x.ArticleId); entity.Property(x => x.ArticleId).HasColumnName("article_id"); entity.Property(x => x.CatId).HasColumnName("cat_id"); entity.Property(x => x.Title).HasColumnName("title"); entity.Property(x => x.Author).HasColumnName("author"); entity.Property(x => x.ArticleDesc).HasColumnName("article_desc"); entity.Property(x => x.Content).HasColumnName("content"); entity.Property(x => x.IsOpen).HasColumnName("is_open"); });
        modelBuilder.Entity<Region>(entity => { entity.ToTable("ecs_region"); entity.HasKey(x => x.RegionId); entity.Property(x => x.RegionId).HasColumnName("region_id"); entity.Property(x => x.ParentId).HasColumnName("parent_id"); entity.Property(x => x.RegionName).HasColumnName("region_name"); entity.Property(x => x.RegionType).HasColumnName("region_type"); });
        modelBuilder.Entity<ShopUser>(e => { e.ToTable("ecs_users"); e.HasKey(x => x.UserId); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.UserName).HasColumnName("user_name"); e.Property(x => x.Email).HasColumnName("email"); e.Property(x => x.PasswordHash).HasColumnName("password_hash"); });
        modelBuilder.Entity<UserSession>(e => { e.ToTable("ecs_sessions"); e.HasKey(x => x.TokenHash); e.Property(x => x.TokenHash).HasColumnName("token_hash"); e.Property(x => x.UserId).HasColumnName("user_id"); });
        modelBuilder.Entity<UserAddress>(e => { e.ToTable("ecs_user_address"); e.HasKey(x => x.AddressId); e.Property(x => x.AddressId).HasColumnName("address_id"); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.Consignee).HasColumnName("consignee"); e.Property(x => x.CountryId).HasColumnName("country_id"); e.Property(x => x.ProvinceId).HasColumnName("province_id"); e.Property(x => x.CityId).HasColumnName("city_id"); e.Property(x => x.DistrictId).HasColumnName("district_id"); e.Property(x => x.Address).HasColumnName("address"); e.Property(x => x.Zipcode).HasColumnName("zipcode"); e.Property(x => x.Mobile).HasColumnName("mobile"); e.Property(x => x.IsDefault).HasColumnName("is_default"); });
        modelBuilder.Entity<CartItem>(e => { e.ToTable("ecs_cart"); e.HasKey(x => x.RecId); e.Property(x => x.RecId).HasColumnName("rec_id"); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.GoodsId).HasColumnName("goods_id"); e.Property(x => x.GoodsNumber).HasColumnName("goods_number"); e.Property(x => x.Version).HasColumnName("version"); e.HasIndex(x => new { x.UserId, x.GoodsId }).IsUnique(); });
        modelBuilder.Entity<ShippingMethod>(e => { e.ToTable("ecs_shipping"); e.HasKey(x => x.ShippingId); e.Property(x => x.ShippingId).HasColumnName("shipping_id"); e.Property(x => x.ShippingName).HasColumnName("shipping_name"); e.Property(x => x.Enabled).HasColumnName("enabled"); e.Property(x => x.ShippingFee).HasColumnName("shipping_fee"); });
        modelBuilder.Entity<PaymentMethod>(e => { e.ToTable("ecs_payment"); e.HasKey(x => x.PayId); e.Property(x => x.PayId).HasColumnName("pay_id"); e.Property(x => x.PayName).HasColumnName("pay_name"); e.Property(x => x.Enabled).HasColumnName("enabled"); e.Property(x => x.PayFee).HasColumnName("pay_fee"); });
        modelBuilder.Entity<ShopOrder>(e => { e.ToTable("ecs_order_info"); e.HasKey(x => x.OrderId); e.Property(x => x.OrderId).HasColumnName("order_id"); e.Property(x => x.OrderSn).HasColumnName("order_sn"); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.OrderStatus).HasColumnName("order_status"); e.Property(x => x.PayStatus).HasColumnName("pay_status"); e.Property(x => x.ShippingStatus).HasColumnName("shipping_status"); e.Property(x => x.Consignee).HasColumnName("consignee"); e.Property(x => x.Address).HasColumnName("address"); e.Property(x => x.ShippingId).HasColumnName("shipping_id"); e.Property(x => x.ShippingName).HasColumnName("shipping_name"); e.Property(x => x.PayId).HasColumnName("pay_id"); e.Property(x => x.PayName).HasColumnName("pay_name"); e.Property(x => x.GoodsAmount).HasColumnName("goods_amount"); e.Property(x => x.ShippingFee).HasColumnName("shipping_fee"); e.Property(x => x.PayFee).HasColumnName("pay_fee"); e.Property(x => x.OrderAmount).HasColumnName("order_amount"); e.Property(x => x.AddTime).HasColumnName("add_time"); e.Property(x => x.ClientRequestId).HasColumnName("client_request_id"); e.HasIndex(x => x.OrderSn).IsUnique(); e.HasIndex(x => new { x.UserId, x.ClientRequestId }).IsUnique(); });
        modelBuilder.Entity<OrderItem>(e => { e.ToTable("ecs_order_goods"); e.HasKey(x => x.RecId); e.Property(x => x.RecId).HasColumnName("rec_id"); e.Property(x => x.OrderId).HasColumnName("order_id"); e.Property(x => x.GoodsId).HasColumnName("goods_id"); e.Property(x => x.GoodsName).HasColumnName("goods_name"); e.Property(x => x.GoodsSn).HasColumnName("goods_sn"); e.Property(x => x.GoodsPrice).HasColumnName("goods_price"); e.Property(x => x.GoodsNumber).HasColumnName("goods_number"); });
        modelBuilder.Entity<OrderAction>(e => { e.ToTable("ecs_order_action"); e.HasKey(x => x.ActionId); e.Property(x => x.ActionId).HasColumnName("action_id"); e.Property(x => x.OrderId).HasColumnName("order_id"); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.ActionNote).HasColumnName("action_note"); e.Property(x => x.LogTime).HasColumnName("log_time"); });
        modelBuilder.Entity<ShopComment>(e => { e.ToTable("ecs_comment"); e.HasKey(x => x.CommentId); e.Property(x => x.CommentId).HasColumnName("comment_id"); e.Property(x => x.GoodsId).HasColumnName("goods_id"); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.Content).HasColumnName("content"); e.Property(x => x.IsVisible).HasColumnName("is_visible"); e.Property(x => x.AddTime).HasColumnName("add_time"); });
        modelBuilder.Entity<PaymentLog>(e => { e.ToTable("ecs_pay_log"); e.HasKey(x => x.LogId); e.Property(x => x.LogId).HasColumnName("log_id"); e.Property(x => x.OrderId).HasColumnName("order_id"); e.Property(x => x.Provider).HasColumnName("provider"); e.Property(x => x.TransactionId).HasColumnName("transaction_id"); e.Property(x => x.PaidAt).HasColumnName("paid_at"); e.HasIndex(x => new { x.Provider, x.TransactionId }).IsUnique(); });
        modelBuilder.Entity<GoodsActivity>(e => { e.ToTable("ecs_goods_activity"); e.HasKey(x => x.ActivityId); e.Property(x => x.ActivityId).HasColumnName("act_id"); e.Property(x => x.ActivityType).HasColumnName("act_type"); e.Property(x => x.ActivityName).HasColumnName("act_name"); e.Property(x => x.GoodsId).HasColumnName("goods_id"); e.Property(x => x.StartTime).HasColumnName("start_time"); e.Property(x => x.EndTime).HasColumnName("end_time"); e.Property(x => x.IsFinished).HasColumnName("is_finished"); });
    }
}
